# Token to log into Discord with. See our installation instructions at https://github.com/Hexaoxide/CarbonCord. | todo comment
# !!! The token is what allows us to log into the bot account !!!
# !!!      **DO NOT SHARE IT UNDER ANY CIRCUMSTANCES**        !!!
bot-token: ""

# todo comments
discord-channel-settings:
  global:
    carbon-channel-key: "global"
    discord-channel-id: "00000000000000"
    key: ""
    to-discord-formats:
      default: "**<username>:** <message>"
    to-carbon-formats:
      default: "<bold><username>: </bold><message>"
    default-format-name: "default"

notification-channel-settings:
  join:
    type: "JOIN"
    format: "**<username> joined the game**"
    key: "join"
    channel-id: "00000000000000"
  leave:
    type: "LEAVE"
    format: "**<username> left the game**"
    key: "leave"
    channel-id: "00000000000000"
  start:
    type: "START"
    format: "**Server has started.**"
    key: "start"
    channel-id: "00000000000000"
  stop:
    type: "STOP"
    format: "**Server has stopped.**"
    key: "stop"
    channel-id: "00000000000000"
  advancement:
    type: "ADVANCEMENT"
    format: "**<username> made the <advancement> advancement!**"
    key: "stop"
    channel-id: "00000000000000"
